Repository TEAM21-2NE1/ticketing, pull requests merged in 2024-10, with the labels that each got.

#12 Chore/#10review config setup
  review/.gitignore
  review/build.gradle
  review/db/.gitkeep
  review/docker-compose-local.yml
  review/src/main/java/com/ticketing/review/common/auditor/BaseEntity.java
  review/src/main/java/com/ticketing/review/common/auditor/JpaAuditingConfig.java
  review/src/main/java/com/ticketing/review/common/auditor/UserAuditorAware.java
  review/src/main/java/com/ticketing/review/common/exception/.gitkeep
  review/src/main/java/com/ticketing/review/common/exception/GlobalExceptionHandelr.java
  review/src/main/java/com/ticketing/review/common/response/.gitkeep
  review/src/main/java/com/ticketing/review/common/response/CommonResponse.java
  review/src/main/java/com/ticketing/review/common/response/ErrorCode.java
  review/src/main/java/com/ticketing/review/infrastructure/configuration/.gitkeep
  review/src/main/java/com/ticketing/review/infrastructure/configuration/PropertyConfig.java
  review/src/main/resources/application-dev.yml
  review/src/main/resources/application-local.yml
  review/src/main/resources/application-prod.yml
  review/src/main/resources/application.yml
Labels: feature

#11 Feat/#7user signup login
  gateway/src/main/resources/application.yml
  user/build.gradle
  user/src/main/java/com/ticketing/user/application/dto/request/CreateUserRequestDto.java
  user/src/main/java/com/ticketing/user/application/dto/request/LoginUserRequestDto.java
  user/src/main/java/com/ticketing/user/application/service/UserService.java
  user/src/main/java/com/ticketing/user/application/service/UserServiceImpl.java
  user/src/main/java/com/ticketing/user/common/auditor/BaseEntity.java
  user/src/main/java/com/ticketing/user/common/auditor/JpaAuditingConfig.java
  user/src/main/java/com/ticketing/user/common/auditor/UserAuditorAware.java
  user/src/main/java/com/ticketing/user/common/exception/GlobalExceptionHandler.java
  user/src/main/java/com/ticketing/user/common/exception/UserException.java
  user/src/main/java/com/ticketing/user/common/response/CommonResponse.java
  user/src/main/java/com/ticketing/user/common/response/ErrorCode.java
  user/src/main/java/com/ticketing/user/common/response/ExceptionResponse.java
  user/src/main/java/com/ticketing/user/common/response/SuccessCode.java
  user/src/main/java/com/ticketing/user/common/response/SuccessResponse.java
  user/src/main/java/com/ticketing/user/domain/model/User.java
  user/src/main/java/com/ticketing/user/domain/model/UserDetailsImpl.java
  user/src/main/java/com/ticketing/user/domain/model/UserRole.java
  user/src/main/java/com/ticketing/user/domain/repository/UserRepository.java
  user/src/main/java/com/ticketing/user/infrastructure/configuration/SecurityConfig.java
  user/src/main/java/com/ticketing/user/infrastructure/jwt/AuthenticationFilter.java
  user/src/main/java/com/ticketing/user/infrastructure/jwt/JwtUtil.java
  user/src/main/java/com/ticketing/user/presentation/controller/AuthController.java
  user/src/main/resources/application.yml
Labels: feature

#18 Feat/#14review crud
  review/src/main/java/com/ticketing/review/application/dto/request/.gitkeep
  review/src/main/java/com/ticketing/review/application/dto/request/CreateReviewRequestDto.java
  review/src/main/java/com/ticketing/review/application/dto/request/UpdateReviewRequestDto.java
  review/src/main/java/com/ticketing/review/application/dto/response/.gitkeep
  review/src/main/java/com/ticketing/review/application/dto/response/CreateReviewResponseDto.java
  review/src/main/java/com/ticketing/review/application/dto/response/DeleteReviewResponseDto.java
  review/src/main/java/com/ticketing/review/application/dto/response/ReviewLikeResponseDto.java
  review/src/main/java/com/ticketing/review/application/dto/response/ReviewListResponseDto.java
  review/src/main/java/com/ticketing/review/application/dto/response/ReviewResponseDto.java
  review/src/main/java/com/ticketing/review/application/dto/response/UpdateReviewResponseDto.java
  review/src/main/java/com/ticketing/review/application/service/.gitkeep
  review/src/main/java/com/ticketing/review/application/service/ReviewLikeService.java
  review/src/main/java/com/ticketing/review/application/service/ReviewService.java
  review/src/main/java/com/ticketing/review/common/auditor/BaseEntity.java
  review/src/main/java/com/ticketing/review/common/exception/BusinessException.java
  review/src/main/java/com/ticketing/review/common/exception/FieldError.java
  review/src/main/java/com/ticketing/review/common/exception/GlobalExceptionHandelr.java
  review/src/main/java/com/ticketing/review/common/exception/GlobalExceptionHandler.java
  review/src/main/java/com/ticketing/review/common/exception/ReviewException.java
  review/src/main/java/com/ticketing/review/common/response/CommonResponse.java
  review/src/main/java/com/ticketing/review/common/response/ErrorCode.java
  review/src/main/java/com/ticketing/review/domain/model/.gitkeep
  review/src/main/java/com/ticketing/review/domain/model/Review.java
  review/src/main/java/com/ticketing/review/domain/model/ReviewLike.java
  review/src/main/java/com/ticketing/review/domain/repository/.gitkeep
  review/src/main/java/com/ticketing/review/domain/repository/ReviewLikeRepository.java
  review/src/main/java/com/ticketing/review/domain/repository/ReviewRepository.java
  review/src/main/java/com/ticketing/review/infrastructure/repository/ReviewLikeRepositoryImpl.java
  review/src/main/java/com/ticketing/review/infrastructure/repository/ReviewRepositoryImpl.java
  review/src/main/java/com/ticketing/review/presentation/controller/.gitkeep
  review/src/main/java/com/ticketing/review/presentation/controller/ReviewController.java
Labels: feature

#24 Feat/#23reivew filter add
  review/src/main/java/com/ticketing/review/application/service/ReviewLikeService.java
  review/src/main/java/com/ticketing/review/application/service/ReviewService.java
  review/src/main/java/com/ticketing/review/common/config/FilterConfig.java
  review/src/main/java/com/ticketing/review/common/context/UserContext.java
  review/src/main/java/com/ticketing/review/common/filter/GlobalAuthFilter.java
  review/src/main/java/com/ticketing/review/presentation/controller/ReviewController.java
Labels: feature

#26 Feat/#13gateway jwt
  gateway/build.gradle
  gateway/src/main/java/com/ticketing/gateway/configuration/SecurityConfig.java
  gateway/src/main/java/com/ticketing/gateway/filter/JwtAuthenticationFilter.java
  gateway/src/main/resources/application.yml
  user/src/main/java/com/ticketing/user/infrastructure/configuration/SecurityConfig.java
  user/src/main/java/com/ticketing/user/presentation/controller/UserController.java
Labels: feature

#31 Feat/#22performance ranking
  performance/src/main/java/com/ticketing/performance/PerformanceApplication.java
  performance/src/main/java/com/ticketing/performance/application/dto/rank/RankingResponseDto.java
  performance/src/main/java/com/ticketing/performance/application/scheduler/RankScheduler.java
  performance/src/main/java/com/ticketing/performance/application/service/RankService.java
  performance/src/main/java/com/ticketing/performance/application/service/SeatService.java
  performance/src/main/java/com/ticketing/performance/domain/repository/RankRepository.java
  performance/src/main/java/com/ticketing/performance/domain/repository/RankRepositoryImpl.java
  performance/src/main/java/com/ticketing/performance/infrastructure/config/RedisConfig.java
  performance/src/main/java/com/ticketing/performance/presentation/controller/RankController.java
  performance/src/main/resources/application.yml
Labels: feature

#33 Refactor/#27review spring security add
  review/build.gradle
  review/src/main/java/com/ticketing/review/application/service/ReviewLikeService.java
  review/src/main/java/com/ticketing/review/application/service/ReviewService.java
  review/src/main/java/com/ticketing/review/common/config/FilterConfig.java
  review/src/main/java/com/ticketing/review/common/configuration/SecurityConfig.java
  review/src/main/java/com/ticketing/review/common/context/UserContext.java
  review/src/main/java/com/ticketing/review/common/exception/GlobalExceptionHandler.java
  review/src/main/java/com/ticketing/review/common/filter/GlobalAuthFilter.java
  review/src/main/java/com/ticketing/review/common/filter/JwtAuthorizationFilter.java
  review/src/main/java/com/ticketing/review/infrastructure/utils/SecurityUtils.java
  review/src/main/java/com/ticketing/review/presentation/controller/ReviewController.java
Labels: refactor

#37 Refactor/#30review rating avg redis
  review/build.gradle
  review/docker-compose-local.yml
  review/src/main/java/com/ticketing/review/application/config/AsyncConfig.java
  review/src/main/java/com/ticketing/review/application/event/AvgRatingEvent.java
  review/src/main/java/com/ticketing/review/application/event/RatingOperation.java
  review/src/main/java/com/ticketing/review/application/event/listener/AvgRatingListener.java
  review/src/main/java/com/ticketing/review/application/service/ReviewService.java
  review/src/main/java/com/ticketing/review/domain/repository/RedisRatingRepository.java
  review/src/main/java/com/ticketing/review/infrastructure/configuration/RedisConfig.java
  review/src/main/java/com/ticketing/review/infrastructure/configuration/RedisScriptConfig.java
  review/src/main/java/com/ticketing/review/infrastructure/repository/RedisRatingRepositoryImpl.java
  review/src/main/resources/application-local.yml
  review/src/main/resources/scripts/getAvgRating.lua
  review/src/main/resources/scripts/saveAvgRating.lua
Labels: refactor

#43 Feat/#42performance get performances
  performance/src/main/java/com/ticketing/performance/application/dto/PageInfo.java
  performance/src/main/java/com/ticketing/performance/application/dto/PageResponse.java
  performance/src/main/java/com/ticketing/performance/application/service/PerformanceService.java
  performance/src/main/java/com/ticketing/performance/domain/repository/CustomPerformanceRepository.java
  performance/src/main/java/com/ticketing/performance/domain/repository/CustomPerformanceRepositoryImpl.java
  performance/src/main/java/com/ticketing/performance/domain/repository/PerformanceRepository.java
  performance/src/main/java/com/ticketing/performance/presentation/controller/PerformanceController.java
  performance/src/main/java/com/ticketing/performance/presentation/dto/performance/PerformanceSearchRequestDto.java
Labels: refactor

#51 Fix/#50performance feignclient error fix
  performance/src/main/java/com/ticketing/performance/domain/repository/PerformanceRepository.java
  performance/src/main/java/com/ticketing/performance/infrastructure/client/OrderClient.java
  performance/src/main/java/com/ticketing/performance/infrastructure/repository/CustomPerformanceRepository.java
  performance/src/main/java/com/ticketing/performance/infrastructure/repository/CustomPerformanceRepositoryImpl.java
  performance/src/main/java/com/ticketing/performance/infrastructure/repository/RankRepositoryImpl.java
Labels: fix

#52 Feat/#47user nickname
  user/src/main/java/com/ticketing/user/application/dto/request/GetNicknamesRequestDto.java
  user/src/main/java/com/ticketing/user/application/dto/response/GetNicknameResponseDto.java
  user/src/main/java/com/ticketing/user/application/service/UserService.java
  user/src/main/java/com/ticketing/user/application/service/UserServiceImpl.java
  user/src/main/java/com/ticketing/user/domain/repository/UserRepository.java
  user/src/main/java/com/ticketing/user/infrastructure/configuration/SecurityConfig.java
  user/src/main/java/com/ticketing/user/presentation/controller/FeignUserController.java
  user/src/main/resources/application-dev.yml
  user/src/main/resources/application-local.yml
  user/src/main/resources/application-prod.yml
  user/src/main/resources/application.yml
Labels: feature

#48 Refactor/#46review querydsl
  review/build.gradle
  review/src/main/java/com/ticketing/review/application/service/ReviewService.java
  review/src/main/java/com/ticketing/review/domain/repository/ReviewRepository.java
  review/src/main/java/com/ticketing/review/domain/repository/ReviewRepositoryCustom.java
  review/src/main/java/com/ticketing/review/infrastructure/configuration/QuerydslConfig.java
  review/src/main/java/com/ticketing/review/infrastructure/repository/ReviewLikeRepositoryImpl.java
  review/src/main/java/com/ticketing/review/infrastructure/repository/ReviewRepositoryImpl.java
Labels: refactor

#53 Chore/#41 cicd
  auth/src/main/resources/application-local.yml
  auth/src/main/resources/application-prod.yml
  auth/src/main/resources/application.yml
  eureka/src/main/resources/application-local.yml
  eureka/src/main/resources/application-prod.yml
  eureka/src/main/resources/application.yml
  gateway/src/main/resources/application-local.yml
  gateway/src/main/resources/application-prod.yml
  gateway/src/main/resources/application.yml
  order/src/main/resources/application-local.yml
  order/src/main/resources/application-prod.yml
  order/src/main/resources/application.yml
  payment/src/main/resources/application-local.yml
  payment/src/main/resources/application-prod.yml
  payment/src/main/resources/application.yml
  performance/src/main/resources/application-local.yml
  performance/src/main/resources/application-prod.yml
  performance/src/main/resources/application.yml
  review/src/main/resources/application-local.yml
  review/src/main/resources/application-prod.yml
  review/src/main/resources/application.yml
  user/src/main/resources/application-dev.yml
  user/src/main/resources/application-local.yml
  user/src/main/resources/application-prod.yml
  user/src/main/resources/application.yml
Labels: chore

#59 Chore/#58 cicd
  .github/workflows/cicd.yml
  Dockerfile
  docker-compose.yml
  eureka/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
  user/src/main/resources/application.yml
Labels: chore

#55 Fix/#54performance fix error
  performance/src/main/java/com/ticketing/performance/application/service/SeatService.java
  performance/src/main/java/com/ticketing/performance/common/response/ErrorCode.java
  performance/src/main/java/com/ticketing/performance/domain/repository/SeatRepository.java
  performance/src/main/java/com/ticketing/performance/presentation/dto/performance/CreatePrfRequestDto.java
Labels: fix

#66 Refactor/#65review env change
  review/src/main/java/com/ticketing/review/infrastructure/configuration/PropertyConfig.java
  review/src/main/resources/application-local.yml
Labels: refactor

#64 Refactor/#63performance seat create refactor
  performance/src/main/java/com/ticketing/performance/application/service/SeatService.java
  performance/src/main/java/com/ticketing/performance/domain/repository/SeatRepository.java
  performance/src/main/java/com/ticketing/performance/infrastructure/repository/SeatJdbcRepository.java
  performance/src/main/java/com/ticketing/performance/infrastructure/repository/SeatJdbcRepositoryImpl.java
  performance/src/main/resources/application-local.yml
Labels: refactor

#79 Fix/#78performance seat get seat fix
  performance/src/main/java/com/ticketing/performance/application/service/PerformanceService.java
  performance/src/main/java/com/ticketing/performance/application/service/SeatService.java
  performance/src/main/java/com/ticketing/performance/common/response/ErrorCode.java
  performance/src/main/java/com/ticketing/performance/presentation/controller/SeatController.java
Labels: fix

#81 Chore/ cicd
  .github/workflows/cicd.yml
  Dockerfile
  docker-compose.yml
  dockerTagAndPush.sh
  eureka/src/main/resources/application-prod.yml
  eureka/src/main/resources/application.yml
  gateway/src/main/resources/application-prod.yml
  gateway/src/main/resources/application.yml
  order/build.gradle
  order/src/main/resources/application-local.yml
  order/src/main/resources/application-prod.yml
  order/src/main/resources/application.yml
  order/src/test/java/com/ticketing/order/OrderApplicationTests.java
  payment/src/main/resources/application-prod.yml
  performance/src/main/resources/application-prod.yml
  review/gradle/wrapper/gradle-wrapper.jar
  review/gradle/wrapper/gradle-wrapper.properties
  review/src/main/resources/application-prod.yml
  user/src/main/java/com/ticketing/user/domain/model/User.java
  user/src/main/resources/application-prod.yml
  user/src/test/java/com/ticketing/user/UserApplicationTests.java
Labels: chore

#101 chore(#100): cicd.yml payment 서비스에서 필요한 환경변수 추가
  .github/workflows/cicd.yml
Labels: chore

#107 Feat/#99review feign client order
  review/src/main/java/com/ticketing/review/application/client/ReviewClient.java
  review/src/main/java/com/ticketing/review/application/client/dto/OrderStatusDto.java
  review/src/main/java/com/ticketing/review/application/service/ReviewService.java
  review/src/main/java/com/ticketing/review/common/response/ErrorCode.java
  review/src/main/java/com/ticketing/review/infrastructure/client/OrderClient.java
  review/src/main/java/com/ticketing/review/infrastructure/client/ReviewClientImpl.java
  review/src/main/java/com/ticketing/review/infrastructure/client/dto/GetOrderStatusResponse.java
Labels: feature, refactor

#128 Fix/#118user bug
  gateway/src/main/java/com/ticketing/gateway/configuration/SecurityConfig.java
  gateway/src/main/java/com/ticketing/gateway/filter/JwtAuthenticationFilter.java
  user/.gitignore
  user/src/main/java/com/ticketing/user/application/dto/request/CreateUserRequestDto.java
  user/src/main/java/com/ticketing/user/common/exception/GlobalExceptionHandler.java
  user/src/main/resources/application-local.yml
Labels: fix

#131 Refactor/#130payment order refactor
  gateway/src/main/java/com/ticketing/gateway/configuration/SecurityConfig.java
  gateway/src/main/java/com/ticketing/gateway/filter/JwtAuthenticationFilter.java
  order/build.gradle
  order/src/main/java/com/ticketing/order/application/dto/response/ViewOrderDto.java
  order/src/main/java/com/ticketing/order/application/service/OrderRUDService.java
  order/src/main/java/com/ticketing/order/config/JwtAuthorizationFilter.java
  order/src/main/java/com/ticketing/order/config/SecurityConfig.java
  order/src/main/java/com/ticketing/order/presentation/controller/OrderViewController.java
  order/src/main/resources/templates/payment.html
  payment/src/main/java/com/ticketing/payment/application/service/PaymentServiceImpl.java
Labels: refactor

#143 Chore/#140cicd kafka
  .github/workflows/cicd.yml
  docker-compose.yml
  performance/src/main/resources/application-prod.yml
  review/src/main/resources/application-prod.yml
Labels: chore

#159 Docs/#145 readme
  README.md
Labels: documentation
